# Generated by Django 5.0.4 on 2024-05-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypizza', '0003_alter_pizza_options_pizza_mypizza_piz_id_4161aa_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
